version: '3.8'

services:
  # Modern Hugo site
  hugo:
    image: klakegg/hugo:ext-alpine
    container_name: franco-hugo
    command: server --bind 0.0.0.0 --buildDrafts --disableFastRender
    volumes:
      - ./hugo-site:/src
    ports:
      - "1313:1313"
    restart: unless-stopped
    environment:
      - HUGO_ENV=development

  # Legacy HTML site
  html:
    image: nginx:alpine
    container_name: franco-html
    volumes:
      - ./legacy-site:/usr/share/nginx/html:ro
    ports:
      - "8888:80"
    restart: unless-stopped
