services:
  # Original HTML site (legacy)
  html-site:
    image: nginx:alpine
    container_name: franco-html
    ports:
      - "8888:80"
    volumes:
      - ./legacy-site:/usr/share/nginx/html:ro
    restart: unless-stopped

  # Hugo development server (modern site)
  hugo-dev:
    image: klakegg/hugo:ext-alpine
    container_name: franco-hugo
    command: server --bind 0.0.0.0 --buildDrafts --disableFastRender
    ports:
      - "1313:1313"
    volumes:
      - ./hugo-site:/src
    working_dir: /src
    environment:
      - HUGO_ENV=development
    restart: unless-stopped
