# Netlify configuration for Franco Frescura Archive
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command - builds the Hugo site with minification
  command = "cd hugo-site && hugo --minify"

  # Publish directory - where the built site files are
  publish = "hugo-site/public"

  # Base directory (optional, but good practice)
  base = ""

[build.environment]
  # Hugo version to use (must match your development version)
  HUGO_VERSION = "0.111.3"

  # Use extended Hugo (required for SCSS/SASS)
  HUGO_ENV = "production"

[context.production]
  command = "cd hugo-site && hugo --minify"

[context.deploy-preview]
  command = "cd hugo-site && hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "cd hugo-site && hugo --minify -b $DEPLOY_PRIME_URL"

# Redirect rules (if needed)
# [[redirects]]
#   from = "/old-path/*"
#   to = "/new-path/:splat"
#   status = 301

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
