baseURL = 'https://francofrescura.sahistory.org.za/'
languageCode = 'en-us'
title = 'Franco Frescura Archive'
theme = 'frescura-academic'

[pagination]
  pagerSize = 10

# Enable GitInfo for last modified dates
enableGitInfo = false

# Enable emoji support
enableEmoji = true

# Table of contents
[markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2

# Markdown rendering
[markup.goldmark.renderer]
  unsafe = true  # Allow HTML in markdown

[params]
  # PaperMod specific
  env = "production"
  description = "A comprehensive digital archive of Franco Frescura's work on South African architecture, urban development, and cultural heritage"
  author = "Franco Frescura"
  keywords = ["Franco Frescura", "South African architecture", "indigenous architecture", "urban development", "cultural heritage", "Xhosa", "Tswana", "Zulu", "Venda", "colonial architecture"]

  # SEO and Social
  images = ["/images/franco-1987.jpg"]
  twitterCard = "summary_large_image"
  twitterSite = "@sahistoryonline"

  # Navigation
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowToc = true
  TocOpen = false

  # Home page
  homeInfoParams.Title = "Franco Frescura Archive"
  homeInfoParams.Content = "A comprehensive digital archive dedicated to the life, work, and legacy of Franco Frescura - architect, academic, graphic artist, and authority on South African indigenous architecture."

  # Search
  fuseOpts.isCaseSensitive = false
  fuseOpts.shouldSort = true
  fuseOpts.threshold = 0.4
  fuseOpts.distance = 100
  fuseOpts.ignoreLocation = true

# Menu structure
[[menus.main]]
  identifier = "biography"
  name = "Biography"
  url = "/biography/"
  weight = 10

[[menus.main]]
  identifier = "architecture"
  name = "Architecture"
  url = "/architecture/"
  weight = 20

[[menus.main]]
  identifier = "indigenous"
  name = "Indigenous"
  parent = "architecture"
  url = "/architecture/indigenous/"
  weight = 21

[[menus.main]]
  identifier = "colonial"
  name = "Colonial"
  parent = "architecture"
  url = "/architecture/colonial/"
  weight = 22

[[menus.main]]
  identifier = "missions"
  name = "Mission Stations"
  parent = "architecture"
  url = "/architecture/mission-stations/"
  weight = 23

[[menus.main]]
  identifier = "conservation"
  name = "Conservation"
  parent = "architecture"
  url = "/architecture/conservation/"
  weight = 24

[[menus.main]]
  identifier = "urban"
  name = "Urban Issues"
  url = "/urban-issues/"
  weight = 30

[[menus.main]]
  identifier = "lectures"
  name = "Lectures"
  url = "/lectures/"
  weight = 40

[[menus.main]]
  identifier = "graphic-work"
  name = "Graphic Work"
  url = "/graphic-work/"
  weight = 50

[[menus.main]]
  identifier = "postal"
  name = "Postal History"
  url = "/postal-history/"
  weight = 60

[[menus.main]]
  identifier = "glossary"
  name = "Glossary"
  url = "/glossary/"
  weight = 70

[[menus.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 80

# Taxonomies (tags and categories)
[taxonomies]
  category = 'categories'
  tag = 'tags'
  region = 'regions'
  topic = 'topics'

# Output formats (JSON for search index)
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

# Sitemap configuration
[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Image processing
[imaging]
  quality = 85
  resampleFilter = "Lanczos"

# Privacy settings
[privacy]
  [privacy.youtube]
    privacyEnhanced = true
