name: Link Check

on:
  # Run on pushes to main and pull requests
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Run weekly to catch broken external links
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  # Allow manual trigger
  workflow_dispatch:

jobs:
  link-check:
    name: Check Internal Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 html2text PyYAML lxml

      - name: Run link analysis
        id: link_check
        run: |
          python3 scripts/analyze_links.py > link_report.txt 2>&1 || true
          cat link_report.txt

          # Check if there are broken links
          if grep -q "❌ Found [1-9]" link_report.txt; then
            echo "broken_links=true" >> $GITHUB_OUTPUT
            echo "::warning::Broken links detected"
          else
            echo "broken_links=false" >> $GITHUB_OUTPUT
            echo "::notice::All links are working"
          fi

      - name: Upload link report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: link-report
          path: link_report.txt
          retention-days: 30

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && steps.link_check.outputs.broken_links == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('link_report.txt', 'utf8');

            const body = `## 🔗 Link Check Results

            ⚠️ Broken links detected in this PR.

            <details>
            <summary>View Report</summary>

            \`\`\`
            ${report}
            \`\`\`

            </details>

            Please fix the broken links before merging.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Fail if broken links found
        if: github.event_name == 'pull_request' && steps.link_check.outputs.broken_links == 'true'
        run: |
          echo "::error::Broken links found. Please fix them before merging."
          exit 1
